FROM frolvlad/alpine-glibc
# Environmental preparation
COPY ./build/libwasmer.so /lib
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib
RUN mkdir -p /root/sidecar/plugins
WORKDIR /root/sidecar

# Copy essential binaries from the bin
COPY ./bin/sidecar /usr/local/bin/

# Generate configuration
RUN sidecar --repo=/root/sidecar init

EXPOSE 44555 44544

CMD ["sidecar", "start"]
