name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release-binary:
    name: Release binary on Linux and Macos
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Binary
        run: make release-binary

      - name: Release Binary
        uses: softprops/action-gh-release@v1
        with:
          files: bin/**.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-docker:
    name: Release sidercar docker image
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go_version: [1.13]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Binary
        run: make release-binary

      - name: Build and push sidercar image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: meshplus/sidercar
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: hub.docker.com
          dockerfile: Dockerfile-sidercar
          tag_names: true